languageCode = "en-us"
title = "stuff"
baseurl = "http://teknofire.net/"
#theme = "aerial"
theme = "hugo-identity-theme"

[author]
  handle = "TeknoFire"
  FirstName = "Will"

[taxonomies]
	tag = "tags"
	category = "categories"
	series = "series"

[params]
  name = "Will Fisher"
  about = "Technical Services Manager &nbsp;&bull;&nbsp; Geek"
  copyright = "2017 Will Fisher"
  #Disable the scrolling background by entering any string for bg_scroll. Enable by leaving bg_scroll empty.
  bg_scroll = ""
  favicon = "favicon.ico"

  # Images settings
  # Icons, backgrounds and avatars folders are placed in theme's static/images folder.
  # You may place your images in corresponding folders and then set only filenames below to
  # change page's appearance

  # Site icons
  favicon_ico = "favicon.ico"
  favicon_ico_sizes = "16x16 32x32"
  appleicon = "apple.png"

  # Additional options to supplement icons served
  #favicon_png = "favicon.png"
  #favicon_png_sizes = "96x96"
  #favicon_svg = "favicon.svg"

  # Link custom assets relative to /static
  #custom_js  = [""]
  #custom_css = ["background.css", "icons.css"]

  # Customization switches
  # Overwrite FontAwesome: see icons.css
  #custom_icons = true
  # Overwrite background: see background.css
  #custom_background = true

  [params.personal]
    # If name is not set, author is used
    name = "Will Fisher"
    # Avatars can be written to images/avatars/
    avatar = "will.jpeg"
    position = "Lead Developer/Technical Services Manager"
    livesIn = ""
    scope = [
        ""
      ]
    biography = """
    Making work delightful
    """


[[params.social]]
  medium = "Twitter"
  icon = "fa-twitter"
  link = "@teknofire"

#[[params.social]]
#  medium = "Facebook"
#  icon = "facebook"
#  link = "#"

#[[params.social]]
#  medium = "Dribbble"
#  icon = "dribbble"
#  link = "#"

[[params.social]]
  medium = "Github"
  icon = "fa-github"
  link = "teknofire"

[[params.social]]
  medium = "Email"
  icon = "fa-envelope-o"
  link = "will@teknofire.net"


# Contact form settings

[params.contact]
  # Since this template is static, the contact form uses www.formspree.io as a
  # proxy. The form makes a POST request to their servers to send the actual
  # email. Visitors can send up to a 1000 emails each month for free.
  #
  # What you need to do for the setup?
  #
  # - set your email address under 'email' below
  # - upload the generated site to your server
  # - send a dummy email yourself to confirm your account
  # - click the confirm link in the email from www.formspree.io
  # - you're done. Happy mailing!

  email = "will@teknofire.net"

  # It is possible to substitute formspring with other providers
  # as an example the mailout plugin from caddy.
  # Provide the post URL for the form and depending on the provider
  # add some custom JS script to finish the implementation.

  #postURL = "https://example.com/mailout/"

  enable = false
  title = "Touch Me!"
  namePlaceholder = "Name"
  emailPlaceholder = "Email"
  messagePlaceholder = "Message"
  buttonText = "Send it"
  success = "Thank you for contacting us."
  error = "Message could not be send. Please contact us at "

  # Add optional form fields to identify contact forms.
  #[[params.contact.fields.hidden]]
  #  name = "someID"
  #  value = "example.com"

  #[[params.contact.fields.hidden]]
  # Special values for name such as "page" and "site" will be autofilled
  #  name = "page"

# Social settings
# You may change these with your social links or add others

# Footer settings
[params.footer]
  # If copyright is not set, author is used
  # copyright = "Innovation inc"

# Page license
[params.license]
  link = "https://creativecommons.org/licenses/by-sa/4.0/legalcode"
  name = "CC-BY-SA-4.0"

# Credits
[[params.credits]]
  # Title is used as URL text
  title = "HTML5UP"
  # Text will be used to explain the credit
  text = "Design by"
  link = "https://html5up.net"
